_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
                - 71
                - 105
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
                - 71
                - 105
            "3":
                - 23
                - 55
            "4": 3.8.20
            "5": 0.18.5
            "6": 4.27.1
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
